cutvars:
  InvMass:
    axisnum: 0
    name: inv_mass
  ML_output_Bkg:
    axisnum: 3
    max:
    - 0.008
    - 0.04
    - 0.10999999999999999
    - 0.2
    - 0.25
    - 0.15000000000000002
    - 0.15000000000000002
    - 0.15000000000000002
    - 0.15000000000000002
    - 0.25
    - 0.19999999999999998
    - 0.35
    - 0.4
    - 0.45000000000000007
    min:
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    name: ML_output_Bkg
  ML_output_Prompt:
    axisnum: 4
    max:
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    min:
    - 0.15000000000000002
    - 0.15000000000000002
    - 0.15000000000000002
    - 0.15000000000000002
    - 0.15000000000000002
    - 0.15000000000000002
    - 0.15000000000000002
    - 0.15000000000000002
    - 0.15000000000000002
    - 0.15000000000000002
    - 0.2
    - 0.15000000000000002
    - 0.15000000000000002
    - 0.15000000000000002
    name: ML_output_Prompt
  Pt:
    axisnum: 1
    max:
    - 1
    - 1.5
    - 2
    - 2.5
    - 3
    - 3.5
    - 4
    - 4.5
    - 5
    - 5.5
    - 6
    - 8
    - 12
    - 24
    min:
    - 0.5
    - 1
    - 1.5
    - 2
    - 2.5
    - 3
    - 3.5
    - 4
    - 4.5
    - 5
    - 5.5
    - 6
    - 8
    - 12
    name: fPt
