cutvars: 
    InvMass: 
        axisnum: 0
        name: 'inv_mass'
    Pt: 
        axisnum: 1
        min: [2,2.5,3,3.5,4,4.5,5,5.5,6,8,12]  #[2.,3.,4.,5.,6.,8.]
        max: [2.5,3,3.5,4,4.5,5,5.5,6,8,12,50] #[3.,4.,5.,6.,8.,50.]
        name: 'fPt'
    ML_output_Prompt:
        axisnum: 999
        min: [0.25,0.2,0.15,0.1,0.1,0.25,0.1,0.1,0.15,0.1,0.1]
        max: [1.,1.,1.,1.,1.,1.,1.,1.,1.,1.,1.,1.,1.,1.]
        name: 'ML_output_Prompt'
    ML_output_Bkg:
        axisnum: 999
        min: [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
        max: [0.009, 0.014,0.02,0.025,0.085, 0.075, 0.055, 0.05, 0.075, 0.175, 0.19]
        name: 'ML_output_Bkg'
