mass: 
    axisnum: 0
    name: 'inv_mass'
pt: 
    axisnum: 1
    min: [1, 2, 4, 6, 8, 12]  #[2.,3.,4.,5.,6.,8.]
    max: [2, 4, 6, 8, 12, 24] #[3.,4.,5.,6.,8.,50.]
    name: 'fPt'
cent: 
    axisnum: 2
    min: [0,   0, 1, 10, 30, 50, 70]  
    max: [100, 1, 10, 30, 50, 70, 100]
    name: 'cent'
ml_output_prompt:
    axisnum: 4
    min: [0.3,  0.3,   0.3,   0.3,  0.3,    0.3]
    max: [1., 1., 1., 1., 1., 1.]
    name: 'ML_output_Prompt'
ml_output_bkg:
    axisnum: 3
    min: [0, 0, 0, 0, 0, 0]
    max: [0.03,  0.08,   0.1,   0.22,  0.25,    0.3]
    name: 'ML_output_Bkg'